language: java

jdk: oraclejdk8

dist: trusty

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

env:
  global:
  - ORG_GRADLE_PROJECT_downloadIdeaSources=false

jobs:
  include:
    - stage: Build and Test
      env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-TRUNK-SNAPSHOT
    - env: ORG_GRADLE_PROJECT_ideaVersion=2018.1.6
    - env: ORG_GRADLE_PROJECT_ideaVersion=2018.1.1
    - stage: Deploy new Release
      if: branch = master
      script: skip
      env: ORG_GRADLE_PROJECT_ideaVersion=2018.1
      deploy:
        provider: script
        skip_cleanup: true
        script: ./gradlew publishPlugin
        on:
          branch: master
  allow_failures:
    - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-TRUNK-SNAPSHOT
