name: Build & Verify

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: IDEA ${{ matrix.idea }} & JDK ${{ matrix.jdk }}
    strategy:
      fail-fast: false
      matrix:
        idea: [ '2020.3', '2020.3.3', '211-EAP-SNAPSHOT' ]
        jdk: [ '11' ]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}

    - name: build & check
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew build check

    - name: buildPlugin
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew buildPlugin
