name: Build & Verify

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: IDEA ${{ matrix.idea }} & JDK ${{ matrix.jdk }}
    strategy:
      fail-fast: false
      matrix:
        idea: [ '2022.1', '2022.1.4', '2022.2', '2022.2.3' ]
        jdk: [ '11' ]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: zulu
        cache: gradle

    - name: build & check
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew build check

    - name: buildPlugin
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew buildPlugin
